server:
  port: 2426

storage:
  location: ${user.home}/.cache/storage-comics

spring:
  output:
      ansi:
        enabled: always
  profiles:
    active: dev
  application:
    name: Comic-Media-Service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

