spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: dev
    password: devpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

aws:
  profile: floci
  region: us-east-1
  accessKey: test
  secretKey: test
  s3:
    endpoint: http://localhost:4566
    comic-storage-bucket-name: comics
    # comic-cover-bucket-name: covers
