spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: dev
    password: devpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
