services:
  db:
    image: postgres:15
    container_name: spring-dev-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../ddl/v1.0-schema-core.sql:/docker-entrypoint-initdb.d/01-schema.sql
  floci:
    image: floci/floci:1.5.18
    container_name: aws-local
    ports:
      - "4566:4566"
volumes:
  db_data: