server {
    listen 80;
    server_name localhost;

    location /comic/ {
        # Ruta interna del contenedor donde se montará el volumen
        alias /usr/share/nginx/html/comic_data/;
        autoindex on; # Útil para pruebas: permite ver la lista de archivos
        
        # Configuraciones para optimizar el servicio de imágenes
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

}